name: Docker build and push

on: [push]

jobs:
  buildPush: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/markdown-to-pdf
          tag_with_sha: true
          tag_with_ref: true
