name: Docker build and push

on: [push]

jobs:
  buildPush: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: markdown-to-pdf:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
