name: Docker build and push

on: [push]

jobs:
  buildPush: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          registry: registry.cmicloud.ch:4443
          repository: markdown-to-pdf
          tag_with_ref: true
          always_pull: true
          add_git_labels: true
          path: .
