name: Docker build and push

on: [push]

jobs:
  buildPush: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com/cminformatik/markdown-to-pdf
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: markdown-to-pdf:latest
